
let productList = [
  {
    name: "Jordan Men's Air 1 Zoom CMFT 2 Muslin/Celestial Gold Black (DV1307 100)",
    images: ["https://m.media-amazon.com/images/I/61Ej7BLAY9L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61QxgUQEYIL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61FRxHYzPcL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/614O6b64S2L._AC_SY695_.jpg"],
    id: 1,
    size: 40,
    status: true,
    brand: "Jordan",
    rating: 4.9,
    sold: 3501,
    price: 3000000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Air Jordan 1 Zoom Cmft 2, Kiểu họa tiết: Màu trơn ",
    type: 1,
  },
  {
    name: "Nike Men's Air Force 1 Low White/White (315122-111)",
    images: ["https://m.media-amazon.com/images/I/618FhFPg8+L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61ZeiaHrtqL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61qryi8QSML._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61ZeiaHrtqL._AC_SX695_.jpg"],
    id: 2,
    size: 42,
    status: true,
    brand: "Nike",
    rating: 4.5,
    sold: 5000,
    price: 2500000,
    sale: 10,
    description: "Kiểu dáng: Giày nam Nike Air Force 1 Low, Kiểu họa tiết: Màu trơn",
    type: 1,
  },
  {
    name: "Adidas Men's Ultraboost 20 Core Black/Gold Metallic (EG0691)",
    images: ["https://m.media-amazon.com/images/I/71hWbPO6gYL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71YWHQTSliL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/819U5FcFAyL._AC_SX695_.jpg"],
    id: 3,
    size: 41,
    status: true,
    brand: "Adidas",
    rating: 4.7,
    sold: 4000,
    price: 2800000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Adidas Ultraboost 20, Kiểu họa tiết: Màu trơn",
    type: 1,
  },
  {
    name: "Converse Chuck Taylor All Star Low Top Black/White (M9166)",
    images: ["https://m.media-amazon.com/images/I/613ExxQ33qL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61vx1+vfOgL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61OFJovXzIL._AC_SY695_.jpg"],
    id: 4,
    size: 39,
    status: true,
    brand: "Converse",
    rating: 4.3,
    sold: 3500,
    price: 1500000,
    sale: 5,
    description: "Kiểu dáng: Giày unisex Converse Chuck Taylor All Star Low Top, Kiểu họa tiết: Màu trơn",
    type: 1,
  },
  {
    name: "Puma Men's RS-X³ Puzzle Puma White/Galaxy Blue (373699-03)",
    images: ["https://m.media-amazon.com/images/I/61bSPAIO43L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51qWzEjBW+L._AC_SY695_.jpg",""],
    id: 5,
    size: 43,
    status: true,
    brand: "Puma",
    rating: 4.2,
    sold: 2800,
    price: 2200000,
    sale: 15,
    description: "Kiểu dáng: Giày nam Puma RS-X³ Puzzle, Kiểu họa tiết: Màu trơn",
    type: 1,
  },
  {
    name: "Vans Old Skool Black/White (VN000D3HY28)",
    images: ["https://m.media-amazon.com/images/I/71pJ6jvT4qL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71W03FhkD0L._AC_SX695_.jpg",""],
    id: 6,
    type: 1,
    size: 38,
    status: true,
    brand: "Vans",
    rating: 4.6,
    sold: 3200,
    price: 1800000,
    sale: 0,
    description: "Kiểu dáng: Giày unisex Vans Old Skool, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "New Balance Men's 997R White/Navy (CM997HCC)",
    images: ["https://m.media-amazon.com/images/I/51nrDTyzCML._AC_SY695_.jpg","https://m.media-amazon.com/images/I/511XUvW8I0L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51v-V7PV8RL._AC_SY695_.jpg"],
    type: 1,
    id: 7,
    size: 42,
    status: true,
    brand: "New Balance",
    rating: 4.4,
    sold: 2100,
    price: 1900000,
    sale: 20,
    description: "Kiểu dáng: Giày nam New Balance 997H, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Reebok Men's Classic Leather White (101)",
    images: ["https://m.media-amazon.com/images/I/51-Q0SUm+2L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51D2iFuXA4L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61W-X1MarPL._AC_SY695_.jpg"],
    type: 1,
    id: 8,
    size: 44,
    status: true,
    brand: "Reebok",
    rating: 4.1,
    sold: 1800,
    price: 1600000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Reebok Classic Leather, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "ASICS Men's GEL-Nimbus 26 White/Black (1011A984-100)",
    images: ["https://m.media-amazon.com/images/I/51paP0wNO6L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51UW1tcRJaL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51IAmKLrO0L._AC_SX695_.jpg"],
    type: 1,
    id: 9,
    size: 45,
    status: true,
    brand: "ASICS",
    rating: 4.8,
    sold: 2500,
    price: 3200000,
    sale: 0,
    description: "Kiểu dáng: Giày nam ASICS GEL-Nimbus 23, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Under Armour Men's HOVR Sonic 5 Black/White (3023489-002)",
    images: ["https://m.media-amazon.com/images/I/61QSO6pGRuL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61Z0plf2bwL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61sq5IEHyAL._AC_SY695_.jpg"],
    type: 1,
    id: 10,
    size: 42,
    status: true,
    brand: "Under Armour",
    rating: 4.3,
    sold: 1800,
    price: 2100000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Under Armour HOVR Sonic 4, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Saucony Men's Ride 17 Black/White (S20545-20)",
    images: ["https://m.media-amazon.com/images/I/51pLtsnCrTL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61fjXH9GceL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/6161xj8HbjL._AC_SY695_.jpg"],
    type: 1,
    id: 11,
    size: 43,
    status: false,
    brand: "Saucony",
    rating: 4.5,
    sold: 2200,
    price: 2400000,
    sale: 10,
    description: "Kiểu dáng: Giày nam Saucony Ride 14, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Brooks Men's Ghost 15 Neutral Black/White (1103491D071)",
    images: ["https://m.media-amazon.com/images/I/71XjYtwZNRL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/71EV02FDHTL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/71UnhmeeavL._AC_SY695_.jpg"],
    type: 1,
    id: 12,
    size: 40,
    status: true,
    brand: "Brooks",
    rating: 4.6,
    sold: 2000,
    price: 2700000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Brooks Ghost 13, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Mizuno Men's Wave Rider 24 White/Black (J1GC200301)",
    images: ["https://m.media-amazon.com/images/I/71BV23j9g7L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71irmBjw-SL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71EmMbD73fL._AC_SX695_.jpg"],
    type: 1,
    id: 13,
    size: 41,
    status: true,
    brand: "Mizuno",
    rating: 4.2,
    sold: 1900,
    price: 2300000,
    sale: 15,
    description: "Kiểu dáng: Giày nam Mizuno Wave Rider 24, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Hoka One One Men's Clifton 7 White/Black (1110508-WBLC)",
    images: ["https://m.media-amazon.com/images/I/61Rd2AfecGL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61mR1ou11qL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/515pzh-U1XL._AC_SY695_.jpg"],
    type: 1,
    id: 14,
    size: 42,
    status: true,
    brand: "Hoka One One",
    rating: 4.7,
    sold: 2800,
    price: 3100000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Hoka One One Clifton 7, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Salomon Men's Speedcross 5 Black/White (L40978000)",
    images: ["https://m.media-amazon.com/images/I/51U4z-mPtyL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61bpMPrInxL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/514PhdgjNrL._AC_SY695_.jpg"],
    type: 1,
    id: 15,
    size: 39,
    status: false,
    brand: "Salomon",
    rating: 4.4,
    sold: 2500,
    price: 2900000,
    sale: 5,
    description: "Kiểu dáng: Giày nam Salomon Speedcross 5, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Merrell Men's Moab 2 Ventilator Walnut (J06011)",
    images: ["https://www.excell-sports.com/images/merrell-mens-moab-3-p34485-364820_thumbmini.jpg","https://www.excell-sports.com/images/merrell-mens-moab-3-p34485-364833_thumbmini.jpg","https://www.excell-sports.com/images/merrell-mens-moab-3-p34485-364859_thumbmini.jpg"],
    type: 1,
    id: 16,
    size: 44,
    status: true,
    brand: "Merrell",
    rating: 4.3,
    sold: 1500,
    price: 1800000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Merrell Moab 2 Ventilator, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Timberland Men's 6-Inch Premium Waterproof Boot Wheat Nubuck (TB010061713)",
    images: ["https://m.media-amazon.com/images/I/81XD879NieL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/81-72PWR34L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/91dESdoWtWL._AC_SY695_.jpg"],
    type: 1,
    id: 17,
    size: 43,
    status: true,
    brand: "Timberland",
    rating: 4.6,
    sold: 3200,
    descriptopm:"Giày nam Timberland 6-Inch Premium Waterproof Boot, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "New Balance Men's Fresh Foam 1080v11 Grey/White (M1080GY11)",
    images: ["https://www.directrunning.co.uk/images/extralarge/New_M1080B11-2E.jpg","https://www.directrunning.co.uk/images/Gallery1/New_M1080B11-2E.jpg ","https://www.directrunning.co.uk/images/Gallery2/New_M1080B11-2E.jpg"],
    type: 1,
    id: 18,
    size: 42,
    status: true,
    brand: "New Balance",
    rating: 4.5,
    sold: 2700,
    price: 2600000,
    sale: 0,
    description: "Kiểu dáng: Giày nam New Balance Fresh Foam 1080v11, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Nike Men's Air Force 1 Low White/Black (315122-111)",
    images: ["https://www.theairmax270.com/wp-content/uploads/2018/09/Nike-Air-Force-1-Low-Tuxedo-Black-White-100x100.jpg","https://www.theairmax270.com/wp-content/uploads/2018/09/Nike-Air-Force-1-Low-Tuxedo-Black-White-1-100x100.jpeg  ","https://www.theairmax270.com/wp-content/uploads/2018/09/Nike-Air-Force-1-Low-Tuxedo-Black-White-6-100x100.jpeg"],
    type: 1,
    id: 19,
    size: 44,
    status: true,
    brand: "Nike",
    rating: 4.7,
    sold: 3500,
    price: 1800000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Nike Air Force 1 Low, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Adidas Men's Ultra Boost 21 Black/White (FY0370)",
    images: ["https://www.cleatshead.com/wp-content/uploads/2022/04/New-Brand-Adidas-Ultra-Boost-21-White-Orange-Black-S23840-Perfect-Outlet-1-100x100.jpg","https://www.cleatshead.com/wp-content/uploads/2022/04/New-Brand-Adidas-Ultra-Boost-21-White-Orange-Black-S23840-Perfect-Outlet-4-600x399-1-100x100.jpg","https://www.cleatshead.com/wp-content/uploads/2022/04/New-Brand-Adidas-Ultra-Boost-21-White-Orange-Black-S23840-Perfect-Outlet-2-600x397-1-100x100.jpg"],
    type: 1,
    id: 20,
    size: 42,
    status: true,
    brand: "Adidas",
    rating: 4.8,
    sold: 2000,
    price: 2500000,
    sale: 0,
    description: "Kiểu dáng: Giày nam Adidas Ultra Boost 21, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Jordan 1 Retro High",
    images: ["https://m.media-amazon.com/images/I/71HlLWaZR+L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/51frI-irzIL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61NIoqW6arL._AC_SY695_.jpg"],
    type: 2,
    id: 21,
    size: 44,
    status: true,
    brand: "Jordan",
    rating: 4.9,
    sold: 3000,
    price: 2800000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Jordan 1 Retro High, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Adidas Ultraboost 21",
    images: ["https://m.media-amazon.com/images/I/61utXtL0sZL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61KGs8Q7xRL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/615LoqB6k4L._AC_SX695_.jpg"],
    type: 2,
    id: 22,
    size: 42,
    status: true,
    brand: "Adidas",
    rating: 4.8,
    sold: 4000,
    price: 2500000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Adidas Ultraboost 21, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Puma Future Rider",
    images: ["https://m.media-amazon.com/images/I/71Grju8PaGL._AC_SY695_.jpg"],
    type: 2,
    id: 23,
    size: 43,
    status: true,
    brand: "Puma",
    rating: 4.5,
    sold: 2800,
    price: 1900000,
    sale: 10,
    description: "Kiểu dáng: Giày thể thao Puma Future Rider, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Reebok Nano X",
    images: ["https://m.media-amazon.com/images/I/71xedIChKlL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71ph5QO5RqL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/619zzJbh-pL._AC_SY695_.jpg  "],
    type: 2,
    id: 24,
    size: 41,
    status: true,
    brand: "Reebok",
    rating: 4.3,
    sold: 2200,
    price: 1500000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Reebok Nano X, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Under Armour HOVR Phantom 2",
    images: ["https://m.media-amazon.com/images/I/41N119AGkCL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/41nmuINHB5L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/41RrqBZ0uQL._AC_SY695_.jpg"],
    type: 2,
    id: 25,
    size: 45,
    status: true,
    brand: "Under Armour",
    rating: 4.6,
    sold: 3200,
    price: 1200000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Under Armour HOVR Phantom 2, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "New Balance Fresh Foam 1080v11",
    images: ["https://m.media-amazon.com/images/I/81SufOfRe4L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/81XIs+HI7eL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/815rGljXbxL._AC_SX695_.jpg"],
    type: 2,
    id: 26,
    size: 42,
    status: true,
    brand: "New Balance",
    rating: 4.4,
    sold: 2800,
    price: 1100000,
    sale: 15,
    description: "Kiểu dáng: Giày thể thao New Balance Fresh Foam 1080v11, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Asics Gel-Kayano 28",
    images: ["https://m.media-amazon.com/images/I/61xanNSN64L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/611lj5IlZrL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61IAjLdHbTL._AC_SY695_.jpg"],
    type: 2,
    id: 27,
    size: 43,
    status: true,
    brand: "Asics",
    rating: 4.2,
    sold: 2400,
    price: 1400000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Asics Gel-Kayano 28, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Salomon Speedcross 5",
    images: ["https://m.media-amazon.com/images/I/71oBbWoqbML._AC_SY695_.jpg","https://m.media-amazon.com/images/I/717uqNRYvLL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/81h7Qm3DC4L._AC_SY695_.jpg"],
    type: 2,
    id: 28,
    size: 40,
    status: true,
    brand: "Salomon",
    rating: 4.7,
    sold: 3000,
    price: 1600000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Salomon Speedcross 5, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Mizuno Wave Rider 25",
    images: ["https://m.media-amazon.com/images/I/71f2kXabJnL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71IkrBVqwAL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/610hscipP3L._AC_SY695_.jpg"],
    type: 2,
    id: 29,
    size: 44,
    status: true,
    brand: "Mizuno",
    rating: 4.5,
    sold: 2000,
    price: 2200000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Mizuno Wave Rider 25, Kiểu họa tiết: Màu trơn"
  },
  {
    name: "Converse Chuck Taylor All Star",
    images: ["https://m.media-amazon.com/images/I/71L+xY5BPHL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71jFxxyNJhL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/618KXZi1OcL._AC_SX695_.jpg"],
    type: 2,
    id: 30,
    size: 39,
    status: true,
    brand: "Converse",
    rating: 4.6,
    sold: 1800,
    price: 900000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Converse Chuck Taylor All Star, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Vans Old Skool",
    images: ["https://m.media-amazon.com/images/I/81H3Z8jeeiL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71VGf81HPTL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71mctIUlYEL._AC_SX695_.jpg"],
    type: 2,
    id: 31,
    size: 42,
    status: true,
    brand: "Vans",
    rating: 4.7,
    sold: 2500,
    price: 1200000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Vans Old Skool, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Nike Air Max 270",
    images: ["https://i8.amplience.net/i/jpl/jd_AH8050-002_C_0001_a?qlt=92&w=160&h=113&v=1&fmt=auto","https://i8.amplience.net/i/jpl/jd_AH8050-002_C_0001_e?qlt=92&w=160&h=113&v=1&fmt=auto","https://i8.amplience.net/i/jpl/jd_AH8050-002_C_0001_b?qlt=92&w=160&h=113&v=1&fmt=auto"],
    type: 2,
    id: 32,
    size: 44,
    status: true,
    brand: "Nike",
    rating: 4.7,
    sold: 3500,
    price: 1800000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Nike Air Max 270, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Puma Suede Classic",
    images: ["https://m.media-amazon.com/images/I/41nDONKfYDL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51QSneqBzKL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/41X9XyW2xLL._AC_SY695_.jpg"],
    type: 2,
    id: 33,
    size: 41,
    status: true,
    brand: "Puma",
    rating: 4.4,
    sold: 2200,
    price: 1100000,
    sale: 20,
    description: "Kiểu dáng: Giày thể thao Puma Suede Classic, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Under Armour Curry 8",
    images: ["https://m.media-amazon.com/images/I/31PQ22P3wHL._AC_.jpg"],
    type: 2,
    id: 34,
    size: 45,
    status: true,
    brand: "Under Armour",
    rating: 4.7,
    sold: 2800,
    price: 1900000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Under Armour Curry 8, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "New Balance 997H",
    images: ["https://m.media-amazon.com/images/I/617NMQ9h7AL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71hPgr-NL1L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71FaUQpcZkL._AC_SX695_.jpg"],
    type: 2,
    id: 35,
    size: 43,
    status: true,
    brand: "New Balance",
    rating: 4.3,
    sold: 2400,
    price: 1500000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao New Balance 997H, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Adidas NMD R1",
    images: ["https://m.media-amazon.com/images/I/71P5mjSf+iL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61UTmzDV2JL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/6113I-oC5vL._AC_SY695_.jpg"],
    type: 2,
    id: 36,
    size: 40,
    status: true,
    brand: "Adidas",
    rating: 4.8,
    sold: 3200,
    price: 2200000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Adidas NMD R1, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Nike Air Force 1",
    images: ["https://m.media-amazon.com/images/I/41MvtTS3T6L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51RGnZB+DTL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/41C5ykdBDlL._AC_SY695_.jpg"],
    type: 2,
    id: 37,
    size: 44,
    status: true,
    brand: "Nike",
    rating: 4.7,
    sold: 3500,
    price: 1600000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Nike Air Force 1, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Adidas Superstar",
    images: ["https://m.media-amazon.com/images/I/511x298LOkL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51XpMRtw9MS._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51A34zuaewL._AC_SY695_.jpg"],
    type: 2,
    id: 38,
    size: 42,
    status: true,
    brand: "Adidas",
    rating: 4.8,
    sold: 4000,
    price: 1400000,
    sale: 10,
    description: "Kiểu dáng: Giày thể thao Adidas Superstar, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Puma RS-X",
    images: ["https://m.media-amazon.com/images/I/616mptnGvoL._AC_SY575_.jpg","https://m.media-amazon.com/images/I/51JWEAqFikL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61skrJAx51L._AC_SY695_.jpg"],
    type: 2,
    id: 39,
    size: 43,
    status: true,
    brand: "Puma",
    rating: 4.5,
    sold: 2800,
    price: 1700000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Puma RS-X, Kiểu họa tiết: Màu trơn",
  },
  {
    name: "Reebok Classic Leather",
    images: ["https://m.media-amazon.com/images/I/51-Q0SUm+2L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/519+F52E6qL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61oNQvRkZ-L._AC_SY695_.jpg"],
    type: 2,
    id: 40,
    size: 41,
    status: true,
    brand: "Reebok",
    rating: 4.3,
    sold: 2200,
    price: 1200000,
    sale: 0,
    description: "Kiểu dáng: Giày thể thao Reebok Classic Leather, Kiểu họa tiết: Màu trơn",
  },
];
localStorage.setItem('productList',JSON.stringify(productList))
let typeList = [
  {
    id:1,
    type: "GIÀY THỂ THAO",
    image :["https://bizweb.dktcdn.net/100/413/756/collections/jordan-2.jpg?v=1617462460240","https://i.pinimg.com/originals/e3/24/90/e324906d9c8a3b0439753b2fc958f83c.jpg","https://img.zcool.cn/community/01486e580872d1a84a0d304f01b339.png@1280w_1l_2o_100sh.png"]
  },
  {
    id: 2,
    type: "GIÀY SNEAKER",
    image : ["https://bizweb.dktcdn.net/100/413/756/collections/jordan-2.jpg?v=1617462460240","https://i.pinimg.com/originals/e3/24/90/e324906d9c8a3b0439753b2fc958f83c.jpg","https://img.zcool.cn/community/01486e580872d1a84a0d304f01b339.png@1280w_1l_2o_100sh.png"],
  },
]
